### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by fcc-drawmaster** [Hazmit/fcc_register_bugs#41]
League registration did not ask about locker rental

**Comment by Hazmit** [comment]
League registration does not ask about locker rental because leagues do not get invoiced until registration closes. Once registration closes for leagues then admins generate all invoices. The invoices do not include locker rentals. When the user receives their e-mail link to their invoice they will click it and be shown their invoice. Just before they see the invoice they answer the "invoice questionnaire" this determines some of their discounts such as youth / student / first time curler and gives them an option to opt in for locker fees and provide their locker number.
