### ISSUE TITLE
Super Sub

### ISSUE THREAD

**Issue by fcc-drawmaster** [Hazmit/fcc_register_bugs#42]
Registering as super sub does not appear to link to any team as a 5th or an available to sub list, but requires full membership.
Also, generates an invoice immediately whereas other methods do not. Invoice includes link to Stripe payment page.

**Comment by Hazmit** [comment]
This is all intended to be this way. Super Subs are a non rostered curler who pay regular member dues because they want to curl. Any registration method that does not put users on a team gets invoiced right away. Being registered on a team does not because multiple registrations take place, we then invoice once when leagues close to bill for all leagues, dues needed.

**Comment by fcc-drawmaster** [comment]
So how do people registered as super subs get to play? There does not seem
to be any way to see who is registered.

**Comment by Hazmit** [comment]
Super subs would only register as a super sub if they are

1. A fifth on a team, they know they won't be playing every week and they are 1-4 on the team registering. They just drop in to curl whenever they can or someone is gone. They need to be a paid curling member but they aren't rostered. It's on them to figure out when they curl.
2. Would be someone who is out of town a lot or just dropping in when they can. They need to pay dues to curl but again aren't rostered on any teams at all. They just find a game when someone needs a sub.
