### ISSUE TITLE
Locked out of registering for a team

### ISSUE THREAD

**Issue by amiller47** [Hazmit/fcc_register_bugs#55]
I said I was a super sub and listed my groups.  Now I changed my mind and found a team.....can't do it because it says I'm already registered, but I have no teams listed.

**Comment by Hazmit** [comment]
This is expected behavior to lock out of other membership signups that you aren't eligible for once you register as a type. This has been made more clear by adding the type you are registered for to the button texts.

![image](https://github.com/Hazmit/fcc_register_bugs/assets/488993/2e6542f0-08bf-4db6-b9ea-1aa31b45fd7d)
